fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    apt:    "git://github.com/puppetlabs/puppetlabs-apt.git"
  symlinks:
    varnish: "#{source_dir}"
