name 'maxchk-varnish'
version '1.0.0'
author 'Max Horlanchuk <max.horlanchuk@gmail.com>'
license 'Apache'
summary 'Varnish module'
description 'Install, configure and manage VCL (Ubuntu/CentOS)'
project_page 'https://github.com/maxchk/puppet-varnish'
dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/concat'
dependency 'puppetlabs/apt'
dependency 'puppetlabs/firewall'
