name 'maxchk-varnish'
version '0.0.6'
author 'Max Horlanchuk <max.horlanchuk@gmail.com>'
license 'Apache'
summary 'Varnish module'
description 'Install, configure and manage VCL'
project_page 'https://github.com/maxchk/puppet-varnish'
